mc = Character(name = "[pName]", who_color = "#FFA500")
e = Character(name = "Eliška", who_color = "#800080")
i = Character(name = "Ivo", who_color= "#90EE90")
im = Character(name = "Ivo's Mum", who_color = "#D3D3D3")
id = Character(name = "Ivo's Dad", who_color = "#D3D3D3")
p = Character(name = "[priestName]", who_color = "#5A5A5A")
