define mc = Character(name = "[pName]", who_color = "#FFA500")
define e = Character(name = "Eliška", who_color = "#800080")
define i = Character(name = "Ivo", who_color= "#90EE90")
define im = Character(name = "Ivo's Mum", who_color = "#D3D3D3")
define ip = Character(name = "Ivo's Dad", who_color = "#D3D3D3")
define p = Character(name = "[priestName]", who_color = "#5A5A5A")
